version: "3.8"

services:
  main-db:
    image: postgres:15
    container_name: tictac-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tictac
      POSTGRES_HOST_AUTH_METHOD: trust
    command: 
      - "postgres"
      - "-c"
      - "log_statement=all"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: tictac-postgres-data
